---
name: updatecli

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run once a day
    - cron: '*/10 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2"

      - name: "Run updatecli in dryrun"
        run: "updatecli diff --config ./updatecli/updatecli.d"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: tibdex/github-app-token@v2.1
        id: generate_token
        if: github.ref == 'refs/heads/v2'
        with:
          app_id: ${{ secrets.UPDATECLIBOT_APP_ID }}
          private_key: ${{ secrets.UPDATECLIBOT_APP_PRIVKEY }}
          
      - name: "Run updatecli"
        run: "updatecli apply --config ./updatecli/updatecli.d"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ secrets.UPDATECLI_BOT_GITHUB_ACTOR }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

