---
name: updatecli
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run once a day
    - cron: '*/10 * * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2.77.0"
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: npm
      - name: "Run updatecli in dryrun"
        run: "updatecli compose diff"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: tibdex/github-app-token@v2.1
        id: generate_token
        if: github.ref == 'refs/heads/main'
        with:
          app_id: ${{ secrets.UPDATECLIBOT_APP_ID }}
          private_key: ${{ secrets.UPDATECLIBOT_APP_PRIVKEY }}
      - name: "Run updatecli"
        run: "updatecli compose apply"
        env:
          GITHUB_ACTOR: ${{ secrets.UPDATECLI_BOT_GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
